// react/vite/designer/src/App.tsx
import ReportDesigner, { RequestOptions} from 'devexpress-reporting-react/dx-report-designer';
import 'devextreme/dist/css/dx.light.css';
import '@devexpress/analytics-core/dist/css/dx-analytics.common.css';
import '@devexpress/analytics-core/dist/css/dx-analytics.light.css';
import 'devexpress-reporting/dist/css/dx-webdocumentviewer.css';
import 'ace-builds/css/ace.css';  
import 'ace-builds/css/theme/dreamweaver.css';  
import 'ace-builds/css/theme/ambiance.css';  
import '@devexpress/analytics-core/dist/css/dx-querybuilder.css';
import 'devexpress-reporting/dist/css/dx-reportdesigner.css';

function App() {

  return (
    <ReportDesigner reportUrl="TestReport">
        <RequestOptions host="http://localhost:5000/" getDesignerModelAction="DXXRD/GetDesignerModel" />
    </ReportDesigner>       
  )
}

export default App

// angular/designer/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { DxReportDesignerModule } from 'devexpress-reporting-angular';
import 'devexpress-reporting/dx-richedit';

@Component({
    selector: 'app-root',
    encapsulation: ViewEncapsulation.None,
    imports: [
        DxReportDesignerModule
    ],
    templateUrl: './app.component.html',
    styleUrls: [
        "../../node_modules/ace-builds/css/ace.css",
        "../../node_modules/ace-builds/css/theme/dreamweaver.css",
        "../../node_modules/ace-builds/css/theme/ambiance.css",
        "../../node_modules/devextreme/dist/css/dx.light.css",
        "../../node_modules/devexpress-richedit/dist/dx.richedit.css",
        "../../node_modules/@devexpress/analytics-core/dist/css/dx-analytics.common.css",
        "../../node_modules/@devexpress/analytics-core/dist/css/dx-analytics.light.css",
        "../../node_modules/@devexpress/analytics-core/dist/css/dx-querybuilder.css",
        "../../node_modules/devexpress-reporting/dist/css/dx-webdocumentviewer.css",
        "../../node_modules/devexpress-reporting/dist/css/dx-reportdesigner.css"
    ]
})
export class AppComponent {
    title = 'DXReportDesignerSample';
    getDesignerModelAction = "/DXXRD/GetDesignerModel"
    // The report name.
    reportName = "TestReport";
    // The backend application URL.
    host = 'http://localhost:5000/';
}
